version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      app-network:
        ipv4_address: 172.20.0.2
    volumes:
      - shared-data:/app/shared

  compile-service:
    build:
      context: ./compile-service
    ports:
      - "8083:8083"
    networks:
      app-network:
        ipv4_address: 172.20.0.3
    volumes:
      - shared-data:/app/shared

  check-solution-service:
    build:
      context: ./check-solution-service
    ports:
      - "8084:8084"
    networks:
      app-network:
        ipv4_address: 172.20.0.4
    volumes:
      - shared-data:/app/shared

  cpp-compiler:
    build:
      context: ./docker/cpp
      dockerfile: DockerfileCpp
    ports:
      - "8085:8085"
    networks:
      app-network:
        ipv4_address: 172.20.0.5
    volumes:
      - shared-data:/app/shared

  cpp-tester:
    build:
      context: ./docker/cpp-tester
      dockerfile: DockerfileTesterCpp
    ports:
      - "8086:8086"
    networks:
      app-network:
        ipv4_address: 172.20.0.6
    volumes:
      - shared-data:/app/shared

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  shared-data:
