version: '3.8'
services:
  api-service:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - shared-data:/app/shared
    depends_on:
      - compiler-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  submission-service:
    build:
      context: ./submission
    ports:
      - "8083:8083"
    volumes:
      - shared-data:/app/shared
    networks:
      - app-network

  checker-service:
    build:
      context: ./checker
    ports:
      - "8084:8084"
    networks:
      - app-network
    volumes:
      - shared-data:/app/shared

  cpp-compiler:
    build:
      context: ./docker/cpp
      dockerfile: DockerfileCpp
    ports:
      - "8085:8085"
    networks:
      - app-network
    volumes:
      - shared-data:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  cpp-tester:
    build:
      context: ./docker/cpp-tester
      dockerfile: DockerfileTesterCpp
    ports:
      - "8086:8086"
    networks:
      - app-network
    volumes:
      - shared-data:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    driver: bridge


volumes:
  shared-data: