#docker-compose up --build - for launch
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"

  cpp-compiler:
    build:
      context: ./docker/cpp
      dockerfile: DockerfileCpp
    volumes:
      - /app
    tty: true
    stdin_open: true

  # Добавьте другие компиляторы аналогично
  # python-compiler:
  #   image: python:latest
  #   volumes:
  #     - /app