version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 3277122228
      MYSQL_DATABASE: ktor_task_tester
      MYSQL_USER: service
      MYSQL_PASSWORD: 3277122228
      MYSQL_BIND_ADDRESS: 0.0.0.0
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  api-service:
    build:
      context: ./api
      dockerfile: Dockerfile
    expose:
      - "8082"
    volumes:
      - shared-data:/app/shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  submission-service:
    build:
      context: ./submission
      dockerfile: Dockerfile
    expose:
      - "8083"
    volumes:
      - shared-data:/app/shared
    networks:
      - app-network

  checker-service:
    build:
      context: ./checker
      dockerfile: Dockerfile
    restart: always
    expose:
      - "8084"
    volumes:
      - shared-data:/app/shared
    networks:
      - app-network

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    expose:
      - "8085"
    volumes:
      - shared-data:/app/shared
    networks:
      - app-network

  task-service:
    build:
      context: ./task
      dockerfile: Dockerfile
    expose:
      - "8086"
    volumes:
      - shared-data:/app/shared
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api-service
      - submission-service
      - checker-service
      - user-service
      - task-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  shared-data:
  mysql_data:
