#docker-compose up --build - for launch
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - app-network
    volumes:
      - shared-data:/app/shared

  compile-service:
    build:
      context: ./compile-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - app-network
    volumes:
      - shared-data:/app/shared


  check-solution-service:
    build:
      context: ./check-solution-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    networks:
      - app-network
    volumes:
      - shared-data:/app/shared

  cpp-compiler:
    build:
      context: ./docker/cpp
      dockerfile: DockerfileCpp
    ports:
      - "8085:8085"
    networks:
      - app-network
    volumes:
      - shared-data:/app/shared

  cpp-tester:
    build:
      context: ./docker/cpp-tester
      dockerfile: DockerfileTesterCpp
    ports:
      - "8086:8086"
    networks:
      - app-network
    volumes:
      - shared-data:/app/shared

networks:
  app-network:
    driver: bridge

volumes:
  shared-data:

  # Добавьте другие компиляторы аналогично
  # python-compiler:
  #   image: python:latest
  #   volumes:
  #     - /app