version: '3.8'
services:
  api-service:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      app-network:
        ipv4_address: 172.20.0.2
    volumes:
      - shared-data:/app/shared

  compiler-service:
    build:
      context: ./compiler
    ports:
      - "8083:8083"
    networks:
      app-network:
        ipv4_address: 172.20.0.3
    volumes:
      - shared-data:/app/shared

  checker-service:
    build:
      context: ./checker
    ports:
      - "8084:8084"
    networks:
      app-network:
        ipv4_address: 172.20.0.4
    volumes:
      - shared-data:/app/shared

  cpp-compiler:
    build:
      context: ./docker/cpp
      dockerfile: DockerfileCpp
    ports:
      - "8085:8085"
    networks:
      app-network:
        ipv4_address: 172.20.0.5
    volumes:
      - shared-data:/app/shared

  cpp-tester:
    build:
      context: ./docker/cpp-tester
      dockerfile: DockerfileTesterCpp
    ports:
      - "8086:8086"
    networks:
      app-network:
        ipv4_address: 172.20.0.6
    volumes:
      - shared-data:/app/shared

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  shared-data:
