ktor:
    application:
        modules:
            - com.sushkpavel.ApplicationKt.module
    deployment:
        port: 8083
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"