ktor:
    application:
        modules:
            - com.sushkpavel.application.ApplicationKt.module
    deployment:
        port: 8082
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"